### PR TITLE
Update for 1.19.2

### LINKED ISSUE #8: 1.19?
Will be there 1.19 version for mod? Any ETA?

### PR DESCRIPTION
**Pull request by solonovamax**
Fixes #8

### CODE REVIEW

**Comment by solonovamax** [comment]
Also, do you think you could add the `hacktoberfest` topic to the repo?

**Comment by Minenash** [comment]
Does this update work:
- In singleplayer
- On a server (installed only clientside)
- On a server (installed only serverside)?

> Also, do you think you could add the hacktoberfest topic to the repo?
I don't think this mod fits, it was made outside of hacktoberfest, and I don't think an inactive mod (which to be fair, not really anything to add to it) having an update during the month of October should count towards being part of a fest

**Comment by solonovamax** [comment]
> Also, do you think you could add the hacktoberfest topic to the repo?
> I don't think this mod fits, it was made outside of hacktoberfest, and I don't think an inactive mod (which to be fair, not really anything to add to it) having an update during the month of October should count towards being part of a fest

I mean, hacktober fest is kinda just about contributing meaningful code to different repos, right? And this is a contribution.

But in the end, up to you.

Also, it 100% works server side only (as that's how I was testing it), and I'm like 95% sure I tested it to make sure it works client side only as well, but I'll double-check later today.

**Comment by solonovamax** [comment]
@Minenash I've tested it in the following configurations:
- Vanilla Client, Modded Server: Works
- Modded Client, Vanilla Server: Works
- Modded Client, Modded Server: Works
- Modded Client, Single Player: Works

Also, I just comitted some changes to clean up the mixin code, and replace the ugly static variables with ducks

**Comment by solonovamax** [comment]
Additionally, I've done a minor bump, because I rewrote some of the internals, so I felt it qualified much more for a minor bump rather than a patch.

**Comment by Minenash** [comment]
Hmm, not 100% I'm on board with all of the changes. Will at least make some changes (like for example, on the server-side implementation, you're currently using two independent methods to make the entity glow at the same time).

But overall, thanks for updating the mod, and I'll release a version tonight!

**Comment by solonovamax** [comment]
> Hmm, not 100% I'm on board with all of the changes. Will at least make some changes (like for example, on the server-side implementation, you're currently using two independent methods to make the entity glow at the same time).

Yeah, the reason I left that was mainly because I couldn't figure out how to get the server to update the client to tell it that the entities were glowing, without giving the entities the glowing effect. However, I wanted to keep the glowing method similar to how it works in single player, so I left both

**Comment by Minenash** [comment]
So, uh small embarrassing moment... I went to create the 1.19 branch to merge this into and... there already was one. Back in August I accepted another dude's PR, fixed the issues with it... and just never made a release. So I'll definitely take some elements from this PR and put them into the 1.19 branch, as they were nice improvements.

*How did I forget to make a release, and then forget that I even did it...*

**Comment by solonovamax** [comment]
gg moment

**Comment by solonovamax** [comment]
I could rebase all of my changes on top of the 1.19 branch & fix any merge conficts, if you'd like

That way, it can be easily merged

**Pull request closed without merging**
