### PR TITLE
Update to 1.18

### LINKED ISSUE #4: 1.18
1.18 Release date?

### PR DESCRIPTION
**Pull request by solonovamax**
Update to 1.18.

Fixes #4.

### CODE REVIEW

**Comment by Minenash** [comment]
Thanks you, so much! Once I land and get to my hotel, I'll test it and merge

**Comment by solonovamax** [comment]
It was a quite simple change. I also made a few other *minor* changes, because I really dislike `static`.

**Comment by Minenash** [comment]
Yeah, I get that, just don't want to release a version before testing it myself. I guess I can merge without making a release though.

I do want to keep the 1.17 and 1.18 branches separate, so I'll probably just clone the branch and rename the one yours target when I'm back from work

**Comment by Pectacular** [comment]
Any progress on the 1.18 update?

**Comment by Giggitybyte** [comment]
👀

**Comment by Minenash** [comment]
Merged and released now. Thanks for this, and so sorry it took me this long to do anything

**Pull request merged**
